/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;



/**
 *
 * @author JoãoHenrique
 */
public class CadastroPastores extends javax.swing.JFrame {

    /**
     * Creates new form ControladorCadastroPastores
     */
    public CadastroPastores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textSobrenome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textDataNascimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        comboCidade = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel9.setText("Cidade");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(446, 180));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Pastor");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(8, 4));

        jLabel2.setText("Id:");
        jPanel2.add(jLabel2);

        textId.setText("Id");
        textId.setEnabled(false);
        jPanel2.add(textId);

        jLabel3.setText("Nome:");
        jPanel2.add(jLabel3);
        jPanel2.add(textNome);

        jLabel4.setText("Sobrenome:");
        jPanel2.add(jLabel4);
        jPanel2.add(textSobrenome);

        jLabel5.setText("CPF:");
        jPanel2.add(jLabel5);
        jPanel2.add(textCpf);

        jLabel6.setText("Data de Nascimento:");
        jPanel2.add(jLabel6);
        jPanel2.add(textDataNascimento);

        jLabel7.setText("Salário:");
        jPanel2.add(jLabel7);
        jPanel2.add(textSalario);

        jLabel8.setText("Estado:");
        jPanel2.add(jLabel8);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboEstado);

        jLabel10.setText("Cidade:");
        jPanel2.add(jLabel10);

        comboCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboCidade);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        btnCadastrar.setText("Cadastrar");
        jPanel8.add(btnCadastrar);

        btnCancelar.setText("Cancelar");
        jPanel8.add(btnCancelar);

        jPanel1.add(jPanel8, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox comboCidade;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textDataNascimento;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textSobrenome;
    // End of variables declaration//GEN-END:variables
 
    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JComboBox getComboCidade() {
        return comboCidade;
    }

    public void setComboCidade(JComboBox comboCidade) {
        this.comboCidade = comboCidade;
    }

    public JComboBox getComboEstado() {
        return comboEstado;
    }

    public void setComboEstado(JComboBox comboEstado) {
        this.comboEstado = comboEstado;
    }

    public JTextField getTextCpf() {
        return textCpf;
    }

    public void setTextCpf(JTextField textCpf) {
        this.textCpf = textCpf;
    }

    public JTextField getTextDataNascimento() {
        return textDataNascimento;
    }

    public void setTextDataNascimento(JTextField textDataNascimento) {
        this.textDataNascimento = textDataNascimento;
    }

    public JTextField getTextId() {
        return textId;
    }

    public void setTextId(JTextField textId) {
        this.textId = textId;
    }

    public JTextField getTextNome() {
        return textNome;
    }

    public void setTextNome(JTextField textNome) {
        this.textNome = textNome;
    }

    public JTextField getTextSalario() {
        return textSalario;
    }

    public void setTextSalario(JTextField textSalario) {
        this.textSalario = textSalario;
    }

    public JTextField getTextSobrenome() {
        return textSobrenome;
    }

    public void setTextSobrenome(JTextField textSobrenome) {
        this.textSobrenome = textSobrenome;
    }


    
}
