/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author JoãoHenrique
 */
public class CadastroTemplos extends javax.swing.JFrame {

    /**
     * Creates new form ControladorCadastroTemplos
     */
    public CadastroTemplos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textCapacidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        comboCidade = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Templo");
        setMaximumSize(new java.awt.Dimension(500, 2147483647));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(471, 200));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnCadastrar.setText("Cadastrar");
        jPanel1.add(btnCadastrar);

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Templo");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel8.setMinimumSize(new java.awt.Dimension(120, 130));
        jPanel8.setPreferredSize(new java.awt.Dimension(120, 130));
        jPanel8.setLayout(new java.awt.GridLayout(8, 4));

        jLabel3.setText("Id:");
        jPanel8.add(jLabel3);

        textId.setText("Id");
        textId.setEnabled(false);
        jPanel8.add(textId);

        jLabel5.setText("Nome:");
        jPanel8.add(jLabel5);
        jPanel8.add(textNome);

        jLabel7.setText("Capacidade:");
        jPanel8.add(jLabel7);
        jPanel8.add(textCapacidade);

        jLabel8.setText("Rua:");
        jPanel8.add(jLabel8);
        jPanel8.add(textRua);

        jLabel9.setText("Número:");
        jPanel8.add(jLabel9);
        jPanel8.add(textNumero);

        jLabel10.setText("Estado:");
        jPanel8.add(jLabel10);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(comboEstado);

        jLabel11.setText("Cidade:");
        jPanel8.add(jLabel11);

        comboCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(comboCidade);

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox comboCidade;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField textCapacidade;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textRua;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JComboBox getComboCidade() {
        return comboCidade;
    }

    public void setComboCidade(JComboBox comboCidade) {
        this.comboCidade = comboCidade;
    }

    public JComboBox getComboEstado() {
        return comboEstado;
    }

    public void setComboEstado(JComboBox comboEstado) {
        this.comboEstado = comboEstado;
    }

    public JTextField getTextCapacidade() {
        return textCapacidade;
    }

    public void setTextCapacidade(JTextField textCapacidade) {
        this.textCapacidade = textCapacidade;
    }

   
    public JTextField getTextId() {
        return textId;
    }

    public void setTextId(JTextField textId) {
        this.textId = textId;
    }

    public JTextField getTextNome() {
        return textNome;
    }

    public void setTextNome(JTextField textNome) {
        this.textNome = textNome;
    }

    public JTextField getTextNumero() {
        return textNumero;
    }

    public void setTextNumero(JTextField textNumero) {
        this.textNumero = textNumero;
    }

    public JTextField getTextRua() {
        return textRua;
    }

    public void setTextRua(JTextField textRua) {
        this.textRua = textRua;
    }
    

}
