/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author JoãoHenrique
 */
public class CadastroFieis extends javax.swing.JFrame {

    /**
     * Creates new form ControladorCadastroFieis
     */
    public CadastroFieis(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public CadastroFieis() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        edtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        edtEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtDataNascimento = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edtRenda = new javax.swing.JFormattedTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edtCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        edtProfissao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtCargo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbEscolaridade = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        edtCelular = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(436, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Fiel");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel8.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        btnCadastrar.setText("Cadastrar");
        jPanel8.add(btnCadastrar);

        btnCancelar.setText("Cancelar");
        jPanel8.add(btnCancelar);

        getContentPane().add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        edtNome.setText("Nome");
        edtNome.setMinimumSize(new java.awt.Dimension(60, 40));
        edtNome.setName(""); // NOI18N
        edtNome.setPreferredSize(new java.awt.Dimension(400, 20));
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(edtNome);

        jLabel4.setText("Estado: ");
        jPanel1.add(jLabel4);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(cmbEstado);

        jLabel11.setText("Cidade: ");
        jPanel1.add(jLabel11);

        cmbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCidade.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(cmbCidade);

        jPanel2.add(jPanel1);

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 55));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        edtEndereco.setText("Rua");
        edtEndereco.setPreferredSize(new java.awt.Dimension(380, 20));
        jPanel10.add(edtEndereco);

        jLabel2.setText("Data de Nascimento: ");
        jPanel10.add(jLabel2);

        edtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        edtDataNascimento.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel10.add(edtDataNascimento);

        jPanel9.setPreferredSize(new java.awt.Dimension(40, 21));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel9);

        jLabel3.setText("Renda : ");
        jPanel10.add(jLabel3);

        edtRenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        edtRenda.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel10.add(edtRenda);

        jPanel14.setPreferredSize(new java.awt.Dimension(30, 21));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel14);

        jPanel2.add(jPanel10);

        jPanel15.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("CPF: ");
        jPanel15.add(jLabel6);

        try {
            edtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCPF.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel15.add(edtCPF);

        jLabel5.setText("Profissão: ");
        jPanel15.add(jLabel5);

        edtProfissao.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel15.add(edtProfissao);

        jLabel7.setText("Cargo: ");
        jPanel15.add(jLabel7);

        edtCargo.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel15.add(edtCargo);

        jLabel8.setText("Escolaridade: ");
        jPanel15.add(jLabel8);

        cmbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEscolaridade.setPreferredSize(new java.awt.Dimension(160, 20));
        jPanel15.add(cmbEscolaridade);

        jPanel2.add(jPanel15);

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("Telefone: ");
        jPanel11.add(jLabel9);

        try {
            edtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtTelefone.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel11.add(edtTelefone);

        jLabel10.setText("Celular:");
        jPanel11.add(jLabel10);

        try {
            edtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCelular.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel11.add(edtCelular);

        jPanel2.add(jPanel11);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(jPanel5);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbCidade;
    private javax.swing.JComboBox cmbEscolaridade;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JFormattedTextField edtCPF;
    private javax.swing.JTextField edtCargo;
    private javax.swing.JFormattedTextField edtCelular;
    private javax.swing.JFormattedTextField edtDataNascimento;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtProfissao;
    private javax.swing.JFormattedTextField edtRenda;
    private javax.swing.JFormattedTextField edtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
    
    public JButton getBtnCancelar(){
        return this.btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }
    
    

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JComboBox getCmbEscolaridade() {
        return cmbEscolaridade;
    }

    public void setCmbEscolaridade(JComboBox cmbEscolaridade) {
        this.cmbEscolaridade = cmbEscolaridade;
    }

    public JComboBox getCmbEstado() {
        return cmbEstado;
    }

    public void setCmbEstado(JComboBox cmbEstado) {
        this.cmbEstado = cmbEstado;
    }

    public JFormattedTextField getEdtCPF() {
        return edtCPF;
    }

    public void setEdtCPF(JFormattedTextField edtCPF) {
        this.edtCPF = edtCPF;
    }

    public JTextField getEdtCargo() {
        return edtCargo;
    }

    public void setEdtCargo(JTextField edtCargo) {
        this.edtCargo = edtCargo;
    }

    public JFormattedTextField getEdtCelular() {
        return edtCelular;
    }

    public void setEdtCelular(JFormattedTextField edtCelular) {
        this.edtCelular = edtCelular;
    }

    public JComboBox getCmbCidade() {
        return cmbCidade;
    }

    public void setCmbCidade(JComboBox cmbCidade) {
        this.cmbCidade = cmbCidade;
    }

    

    public JFormattedTextField getEdtDataNascimento() {
        return edtDataNascimento;
    }

    public void setEdtDataNascimento(JFormattedTextField edtDataNascimento) {
        this.edtDataNascimento = edtDataNascimento;
    }

    public JTextField getEdtEndereco() {
        return edtEndereco;
    }

    public void setEdtEndereco(JTextField edtEndereco) {
        this.edtEndereco = edtEndereco;
    }

    public JTextField getEdtNome() {
        return edtNome;
    }

    public void setEdtNome(JTextField edtNome) {
        this.edtNome = edtNome;
    }

    public JTextField getEdtProfissao() {
        return edtProfissao;
    }

    public void setEdtProfissao(JTextField edtProfissao) {
        this.edtProfissao = edtProfissao;
    }

    public JFormattedTextField getEdtRenda() {
        return edtRenda;
    }

    public void setEdtRenda(JFormattedTextField edtRenda) {
        this.edtRenda = edtRenda;
    }

    public JFormattedTextField getEdtTelefone() {
        return edtTelefone;
    }

    public void setEdtTelefone(JFormattedTextField edtTelefone) {
        this.edtTelefone = edtTelefone;
    }
    
    
}
