/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author JoãoHenrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPastor = new javax.swing.JButton();
        btnTemplo = new javax.swing.JButton();
        btnFiel = new javax.swing.JButton();
        btnFrase = new javax.swing.JButton();
        btnTerreno = new javax.swing.JButton();
        btnCEO = new javax.swing.JButton();
        btnDizimo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnPastor = new javax.swing.JMenuItem();
        mnTemplo = new javax.swing.JMenuItem();
        mnFiel = new javax.swing.JMenuItem();
        mnFrase = new javax.swing.JMenuItem();
        mnTerreno = new javax.swing.JMenuItem();
        mnDizimo = new javax.swing.JMenuItem();
        mnCEO = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuClientesRelatorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arrecada Mais v.6.6.6");
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setLayout(new java.awt.GridLayout(7, 1, 2, 5));

        btnPastor.setText("Pastor");
        jPanel2.add(btnPastor);

        btnTemplo.setText("Templo");
        btnTemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemploActionPerformed(evt);
            }
        });
        jPanel2.add(btnTemplo);

        btnFiel.setText("Fiel");
        jPanel2.add(btnFiel);

        btnFrase.setText("Frase");
        jPanel2.add(btnFrase);

        btnTerreno.setText("Terreno");
        jPanel2.add(btnTerreno);

        btnCEO.setText("C.E.O");
        jPanel2.add(btnCEO);

        btnDizimo.setText("Dízimo");
        btnDizimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDizimoActionPerformed(evt);
            }
        });
        jPanel2.add(btnDizimo);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/arrecadamais/view/MEDIA/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Arquivo");

        mnSair.setText("Sair");
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Entidade");

        mnPastor.setText("Pastor");
        jMenu3.add(mnPastor);

        mnTemplo.setText("Templo");
        jMenu3.add(mnTemplo);

        mnFiel.setText("Fiel");
        jMenu3.add(mnFiel);

        mnFrase.setText("Frase");
        mnFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFraseActionPerformed(evt);
            }
        });
        jMenu3.add(mnFrase);

        mnTerreno.setText("Terreno");
        jMenu3.add(mnTerreno);

        mnDizimo.setText("Dízimo");
        jMenu3.add(mnDizimo);

        mnCEO.setText("Contribuições Espontaneas Obrigatórias");
        mnCEO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCEOActionPerformed(evt);
            }
        });
        jMenu3.add(mnCEO);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu4.add(mnSobre);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Relatório");

        menuClientesRelatorios.setText("Clientes");
        menuClientesRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesRelatoriosActionPerformed(evt);
            }
        });
        jMenu2.add(menuClientesRelatorios);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnFraseActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnSobreActionPerformed

    private void mnCEOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCEOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCEOActionPerformed

    private void btnTemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemploActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTemploActionPerformed

    private void btnDizimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDizimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDizimoActionPerformed

    private void menuClientesRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClientesRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCEO;
    private javax.swing.JButton btnDizimo;
    private javax.swing.JButton btnFiel;
    private javax.swing.JButton btnFrase;
    private javax.swing.JButton btnPastor;
    private javax.swing.JButton btnTemplo;
    private javax.swing.JButton btnTerreno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuClientesRelatorios;
    private javax.swing.JMenuItem mnCEO;
    private javax.swing.JMenuItem mnDizimo;
    private javax.swing.JMenuItem mnFiel;
    private javax.swing.JMenuItem mnFrase;
    private javax.swing.JMenuItem mnPastor;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JMenuItem mnTemplo;
    private javax.swing.JMenuItem mnTerreno;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCEO() {
        return btnCEO;
    }

    public void setBtnCEO(JButton btnCEO) {
        this.btnCEO = btnCEO;
    }

    public JButton getBtnDizimo() {
        return btnDizimo;
    }

    public void setBtnDizimo(JButton btnDizimo) {
        this.btnDizimo = btnDizimo;
    }

    public JButton getBtnFiel() {
        return btnFiel;
    }

    public void setBtnFiel(JButton btnFiel) {
        this.btnFiel = btnFiel;
    }

    public JButton getBtnFrase() {
        return btnFrase;
    }

    public void setBtnFrase(JButton btnFrase) {
        this.btnFrase = btnFrase;
    }

    public JButton getBtnPastor() {
        return btnPastor;
    }

    public void setBtnPastor(JButton btnPastor) {
        this.btnPastor = btnPastor;
    }

    public JButton getBtnTemplo() {
        return btnTemplo;
    }

    public void setBtnTemplo(JButton btnTemplo) {
        this.btnTemplo = btnTemplo;
    }

    public JButton getBtnTerreno() {
        return btnTerreno;
    }

    public void setBtnTerreno(JButton btnTerreno) {
        this.btnTerreno = btnTerreno;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JMenuItem getMnCEO() {
        return mnCEO;
    }

    public void setMnCEO(JMenuItem mnCEO) {
        this.mnCEO = mnCEO;
    }

    public JMenuItem getMnDizimo() {
        return mnDizimo;
    }

    public void setMnDizimo(JMenuItem mnDizimo) {
        this.mnDizimo = mnDizimo;
    }

    public JMenuItem getMnFiel() {
        return mnFiel;
    }

    public void setMnFiel(JMenuItem mnFiel) {
        this.mnFiel = mnFiel;
    }

    public JMenuItem getMnFrase() {
        return mnFrase;
    }

    public void setMnFrase(JMenuItem mnFrase) {
        this.mnFrase = mnFrase;
    }

    public JMenuItem getMnPastor() {
        return mnPastor;
    }

    public void setMnPastor(JMenuItem mnPastor) {
        this.mnPastor = mnPastor;
    }

    public JMenuItem getMnSair() {
        return mnSair;
    }

    public void setMnSair(JMenuItem mnSair) {
        this.mnSair = mnSair;
    }

    public JMenuItem getMnSobre() {
        return mnSobre;
    }

    public void setMnSobre(JMenuItem mnSobre) {
        this.mnSobre = mnSobre;
    }

    public JMenuItem getMnTemplo() {
        return mnTemplo;
    }

    public void setMnTemplo(JMenuItem mnTemplo) {
        this.mnTemplo = mnTemplo;
    }

    public JMenuItem getMnTerreno() {
        return mnTerreno;
    }

    public void setMnTerreno(JMenuItem mnTerreno) {
        this.mnTerreno = mnTerreno;
    }

    public JMenuItem getMenuClientesRelatorios() {
        return menuClientesRelatorios;
    }

    public void setMenuClientesRelatorios(JMenuItem menuClientesRelatorios) {
        this.menuClientesRelatorios = menuClientesRelatorios;
    }
    
    
    
}
