/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view;

/**
 *
 * @author JoãoHenrique
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPastor = new javax.swing.JButton();
        btnTemplo = new javax.swing.JButton();
        btnFiel = new javax.swing.JButton();
        btnFrase = new javax.swing.JButton();
        btnTerreno = new javax.swing.JButton();
        btnCEO = new javax.swing.JButton();
        btnDizimo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnPastor = new javax.swing.JMenuItem();
        mnTemplo = new javax.swing.JMenuItem();
        mnFiel = new javax.swing.JMenuItem();
        mnFrase = new javax.swing.JMenuItem();
        mnTerreno = new javax.swing.JMenuItem();
        mnDizimo = new javax.swing.JMenuItem();
        mnCEO = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arrecada Mais v.6.6.6");
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setLayout(new java.awt.GridLayout(7, 1, 2, 5));

        btnPastor.setText("Pastor");
        jPanel2.add(btnPastor);

        btnTemplo.setText("Templo");
        btnTemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemploActionPerformed(evt);
            }
        });
        jPanel2.add(btnTemplo);

        btnFiel.setText("Fiel");
        jPanel2.add(btnFiel);

        btnFrase.setText("Frase");
        jPanel2.add(btnFrase);

        btnTerreno.setText("Terreno");
        jPanel2.add(btnTerreno);

        btnCEO.setText("C.E.O");
        jPanel2.add(btnCEO);

        btnDizimo.setText("Dízimo");
        btnDizimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDizimoActionPerformed(evt);
            }
        });
        jPanel2.add(btnDizimo);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/arrecadamais/view/MEDIA/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Arquivo");

        mnSair.setText("Sair");
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Entidade");

        mnPastor.setText("Pastor");
        jMenu3.add(mnPastor);

        mnTemplo.setText("Templo");
        jMenu3.add(mnTemplo);

        mnFiel.setText("Fiel");
        jMenu3.add(mnFiel);

        mnFrase.setText("Frase");
        mnFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFraseActionPerformed(evt);
            }
        });
        jMenu3.add(mnFrase);

        mnTerreno.setText("Terreno");
        jMenu3.add(mnTerreno);

        mnDizimo.setText("Dízimo");
        jMenu3.add(mnDizimo);

        mnCEO.setText("Contribuições Espontaneas Obrigatórias");
        mnCEO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCEOActionPerformed(evt);
            }
        });
        jMenu3.add(mnCEO);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu4.add(mnSobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnFraseActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnSobreActionPerformed

    private void mnCEOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCEOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCEOActionPerformed

    private void btnTemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemploActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTemploActionPerformed

    private void btnDizimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDizimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDizimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCEO;
    private javax.swing.JButton btnDizimo;
    private javax.swing.JButton btnFiel;
    private javax.swing.JButton btnFrase;
    private javax.swing.JButton btnPastor;
    private javax.swing.JButton btnTemplo;
    private javax.swing.JButton btnTerreno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mnCEO;
    private javax.swing.JMenuItem mnDizimo;
    private javax.swing.JMenuItem mnFiel;
    private javax.swing.JMenuItem mnFrase;
    private javax.swing.JMenuItem mnPastor;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JMenuItem mnTemplo;
    private javax.swing.JMenuItem mnTerreno;
    // End of variables declaration//GEN-END:variables
}
