/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view.cadastros;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author JoãoHenrique
 */
public class CadastroFieis extends javax.swing.JFrame {

    /**
     * Creates new form ControladorCadastroFieis
     */
    public CadastroFieis(Frame parent, boolean modal) {
        
        initComponents();
    }
    public CadastroFieis() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textSobrenome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textDataNascimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textRenda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textProfissao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textCargo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textEscolaridade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textEdereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        comboCidade = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/arrecadamais/view/MEDIA/ViewFiel.png"))); // NOI18N
        jLabel1.setText("Cadastrar");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel8.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        btnCadastrar.setText("Cadastrar");
        jPanel8.add(btnCadastrar);

        btnCancelar.setText("Cancelar");
        jPanel8.add(btnCancelar);

        getContentPane().add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel6.setLayout(new java.awt.GridLayout(15, 4));

        jLabel12.setText("Id:");
        jPanel6.add(jLabel12);

        textId.setText("Id");
        textId.setEnabled(false);
        jPanel6.add(textId);

        jLabel3.setText("Nome:");
        jPanel6.add(jLabel3);
        jPanel6.add(textNome);

        jLabel13.setText("Sobrenome:");
        jPanel6.add(jLabel13);
        jPanel6.add(textSobrenome);

        jLabel18.setText("Telefone:");
        jPanel6.add(jLabel18);
        jPanel6.add(textTelefone);

        jLabel19.setText("Celular: ");
        jPanel6.add(jLabel19);
        jPanel6.add(textCelular);

        jLabel5.setText("CPF:");
        jPanel6.add(jLabel5);
        jPanel6.add(textCpf);

        jLabel6.setText("Data de Nascimento:");
        jPanel6.add(jLabel6);
        jPanel6.add(textDataNascimento);

        jLabel7.setText("Renda: ");
        jPanel6.add(jLabel7);
        jPanel6.add(textRenda);

        jLabel14.setText("Profissão: ");
        jPanel6.add(jLabel14);
        jPanel6.add(textProfissao);

        jLabel15.setText("Cargo: ");
        jPanel6.add(jLabel15);
        jPanel6.add(textCargo);

        jLabel16.setText("Escolaridade: ");
        jPanel6.add(jLabel16);
        jPanel6.add(textEscolaridade);

        jLabel17.setText("Endereço: ");
        jPanel6.add(jLabel17);
        jPanel6.add(textEdereco);

        jLabel8.setText("Estado:");
        jPanel6.add(jLabel8);

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(comboEstado);

        jLabel10.setText("Cidade:");
        jPanel6.add(jLabel10);

        comboCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(comboCidade);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox comboCidade;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField textCargo;
    private javax.swing.JTextField textCelular;
    private javax.swing.JTextField textCpf;
    private javax.swing.JTextField textDataNascimento;
    private javax.swing.JTextField textEdereco;
    private javax.swing.JTextField textEscolaridade;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textProfissao;
    private javax.swing.JTextField textRenda;
    private javax.swing.JTextField textSobrenome;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables


    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

   

    public JComboBox getComboCidade() {
        return comboCidade;
    }

    public void setComboCidade(JComboBox comboCidade) {
        this.comboCidade = comboCidade;
    }

    public JComboBox getComboEstado() {
        return comboEstado;
    }

    public void setComboEstado(JComboBox comboEstado) {
        this.comboEstado = comboEstado;
    }

    public JTextField getTextCargo() {
        return textCargo;
    }

    public void setTextCargo(JTextField textCargo) {
        this.textCargo = textCargo;
    }

    public JTextField getTextCelular() {
        return textCelular;
    }

    public void setTextCelular(JTextField textCelular) {
        this.textCelular = textCelular;
    }

    public JTextField getTextCpf() {
        return textCpf;
    }

    public void setTextCpf(JTextField textCpf) {
        this.textCpf = textCpf;
    }

    public JTextField getTextDataNascimento() {
        return textDataNascimento;
    }

    public void setTextDataNascimento(JTextField textDataNascimento) {
        this.textDataNascimento = textDataNascimento;
    }

    public JTextField getTextEdereco() {
        return textEdereco;
    }

    public void setTextEdereco(JTextField textEdereco) {
        this.textEdereco = textEdereco;
    }

    public JTextField getTextEscolaridade() {
        return textEscolaridade;
    }

    public void setTextEscolaridade(JTextField textEscolaridade) {
        this.textEscolaridade = textEscolaridade;
    }

    public JTextField getTextId() {
        return textId;
    }

    public void setTextId(JTextField textId) {
        this.textId = textId;
    }

    public JTextField getTextNome() {
        return textNome;
    }

    public void setTextNome(JTextField textNome) {
        this.textNome = textNome;
    }

    public JTextField getTextProfissao() {
        return textProfissao;
    }

    public void setTextProfissao(JTextField textProfissao) {
        this.textProfissao = textProfissao;
    }

    public JTextField getTextRenda() {
        return textRenda;
    }

    public void setTextRenda(JTextField textRenda) {
        this.textRenda = textRenda;
    }

    public JTextField getTextSobrenome() {
        return textSobrenome;
    }

    public void setTextSobrenome(JTextField textSobrenome) {
        this.textSobrenome = textSobrenome;
    }

    public JTextField getTextTelefone() {
        return textTelefone;
    }

    public void setTextTelefone(JTextField textTelefone) {
        this.textTelefone = textTelefone;
    }
}
            
