/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.utfpr.arrecadamais.view.transacoes;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author JoãoHenrique
 */
public class CompraTerrenos extends javax.swing.JFrame {

    /**
     * Creates new form CompraTerrenos
     */
    public CompraTerrenos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        etNumeroCartao = new javax.swing.JFormattedTextField();
        etNomeCartao = new javax.swing.JTextField();
        edCodigoSeguraca = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        edDataValidade = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbTipoTerreno = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbTipoDecoracao = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbNumeroParcela = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        lbJuros = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edLargura = new javax.swing.JTextField();
        edComprimento = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        slComprimento = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        slLargura = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel12.setMaximumSize(new java.awt.Dimension(610, 32767));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(4, 3, 5, 3));

        jLabel14.setText("Número do Cartão:");
        jPanel12.add(jLabel14);

        jLabel15.setText("Nome no Cartão:");
        jPanel12.add(jLabel15);

        jLabel16.setText("Código de Segurança:");
        jPanel12.add(jLabel16);

        etNumeroCartao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####-####-####-####"))));
        jPanel12.add(etNumeroCartao);
        jPanel12.add(etNomeCartao);

        edCodigoSeguraca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        edCodigoSeguraca.setMaximumSize(new java.awt.Dimension(20, 2147483647));
        jPanel12.add(edCodigoSeguraca);

        jLabel17.setText("Data de Validade (MM, AA):");
        jPanel12.add(jLabel17);
        jPanel12.add(jSeparator1);
        jPanel12.add(jSeparator2);

        edDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/YY"))));
        jPanel12.add(edDataValidade);

        jButton1.setText("Comprar para mim");
        jPanel12.add(jButton1);

        jButton2.setText("Comprar para Presente");
        jPanel12.add(jButton2);

        getContentPane().add(jPanel12, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("  Comprar Terreno Celestial");
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("       \"Abençoado sejais aqueles que se unirem ao Grande Arquiteto em seu Empreendimento celestial.\"");
        jPanel2.add(jLabel2);

        jLabel3.setText("             Livro de Malafáia Cap 3 Versículo 89");
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(350, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(350, 274));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 8, 26));

        jLabel8.setText("Escolha o tipo de Terreno:");
        jPanel4.add(jLabel8);

        cbTipoTerreno.setMaximumSize(new java.awt.Dimension(250, 32767));
        cbTipoTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoTerrenoActionPerformed(evt);
            }
        });
        jPanel4.add(cbTipoTerreno);

        jLabel9.setText("Escolha o Tipo de Decoração:");
        jPanel4.add(jLabel9);

        cbTipoDecoracao.setMaximumSize(new java.awt.Dimension(250, 32767));
        jPanel4.add(cbTipoDecoracao);

        jLabel10.setText("Valor total:");
        jPanel4.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jLabel11);

        jLabel12.setText("Número de Parcelas:");
        jPanel4.add(jLabel12);

        cbNumeroParcela.setMaximumSize(new java.awt.Dimension(250, 32767));
        jPanel4.add(cbNumeroParcela);

        jLabel13.setText("Com % de Juros Insignificantes.");
        jPanel4.add(jLabel13);
        jPanel4.add(lbJuros);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamanho e Proporções: "));
        jPanel6.setMaximumSize(new java.awt.Dimension(350, 2147483647));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 5));
        jPanel9.setForeground(new java.awt.Color(102, 255, 102));
        jPanel9.setMinimumSize(new java.awt.Dimension(10, 10));
        jPanel9.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel9.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setText("Comprimento:");

        jLabel5.setText("Largura:");

        edLargura.setEditable(false);
        edLargura.setText("46");
        edLargura.setEnabled(false);
        edLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edLarguraActionPerformed(evt);
            }
        });

        edComprimento.setEditable(false);
        edComprimento.setText("58");
        edComprimento.setEnabled(false);
        edComprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edComprimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(edLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(4, 0));

        jLabel6.setText("Comprimento:");
        jPanel8.add(jLabel6);

        slComprimento.setMaximum(1000);
        slComprimento.setMinimum(10);
        jPanel8.add(slComprimento);

        jLabel7.setText("Largura:");
        jPanel8.add(jLabel7);

        slLargura.setMaximum(1000);
        slLargura.setMinimum(10);
        jPanel8.add(slLargura);

        jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel6);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edLarguraActionPerformed

    private void edComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edComprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edComprimentoActionPerformed

    private void cbTipoTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoTerrenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraTerrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraTerrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraTerrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraTerrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraTerrenos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbNumeroParcela;
    private javax.swing.JComboBox cbTipoDecoracao;
    private javax.swing.JComboBox cbTipoTerreno;
    private javax.swing.JFormattedTextField edCodigoSeguraca;
    private javax.swing.JTextField edComprimento;
    private javax.swing.JFormattedTextField edDataValidade;
    private javax.swing.JTextField edLargura;
    private javax.swing.JTextField etNomeCartao;
    private javax.swing.JFormattedTextField etNumeroCartao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbJuros;
    private javax.swing.JSlider slComprimento;
    private javax.swing.JSlider slLargura;
    // End of variables declaration//GEN-END:variables

    public JComboBox getCbNumeroParcela() {
        return cbNumeroParcela;
    }

    public void setCbNumeroParcela(JComboBox cbNumeroParcela) {
        this.cbNumeroParcela = cbNumeroParcela;
    }

    public JComboBox getCbTipoDecoracao() {
        return cbTipoDecoracao;
    }

    public void setCbTipoDecoracao(JComboBox cbTipoDecoracao) {
        this.cbTipoDecoracao = cbTipoDecoracao;
    }

    public JComboBox getCbTipoTerreno() {
        return cbTipoTerreno;
    }

    public void setCbTipoTerreno(JComboBox cbTipoTerreno) {
        this.cbTipoTerreno = cbTipoTerreno;
    }

    public JFormattedTextField getEdCodigoSeguraca() {
        return edCodigoSeguraca;
    }

    public void setEdCodigoSeguraca(JFormattedTextField edCodigoSeguraca) {
        this.edCodigoSeguraca = edCodigoSeguraca;
    }

    public JTextField getEdComprimento() {
        return edComprimento;
    }

    public void setEdComprimento(JTextField edComprimento) {
        this.edComprimento = edComprimento;
    }

    public JFormattedTextField getEdDataValidade() {
        return edDataValidade;
    }

    public void setEdDataValidade(JFormattedTextField edDataValidade) {
        this.edDataValidade = edDataValidade;
    }

    public JTextField getEdLargura() {
        return edLargura;
    }

    public void setEdLargura(JTextField edLargura) {
        this.edLargura = edLargura;
    }

    public JTextField getEtNomeCartao() {
        return etNomeCartao;
    }

    public void setEtNomeCartao(JTextField etNomeCartao) {
        this.etNomeCartao = etNomeCartao;
    }

    public JFormattedTextField getEtNumeroCartao() {
        return etNumeroCartao;
    }

    public void setEtNumeroCartao(JFormattedTextField etNumeroCartao) {
        this.etNumeroCartao = etNumeroCartao;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel12() {
        return jPanel12;
    }

    public void setjPanel12(JPanel jPanel12) {
        this.jPanel12 = jPanel12;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public void setjPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    public JPanel getjPanel7() {
        return jPanel7;
    }

    public void setjPanel7(JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    public JPanel getjPanel8() {
        return jPanel8;
    }

    public void setjPanel8(JPanel jPanel8) {
        this.jPanel8 = jPanel8;
    }

    public JPanel getjPanel9() {
        return jPanel9;
    }

    public void setjPanel9(JPanel jPanel9) {
        this.jPanel9 = jPanel9;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JSlider getSlComprimento() {
        return slComprimento;
    }

    public void setSlComprimento(JSlider slComprimento) {
        this.slComprimento = slComprimento;
    }

    public JSlider getSlLargura() {
        return slLargura;
    }

    public void setSlLargura(JSlider slLargura) {
        this.slLargura = slLargura;
    }

    public JLabel getLbJuros() {
        return lbJuros;
    }

    public void setLbJuros(JLabel lbJuros) {
        this.lbJuros = lbJuros;
    }
            
            
        
        
}
